import { AircraftModelType, AircraftLiveryConfig } from './types';

export const AIRCRAFT_LIVERIES: Record<AircraftModelType, AircraftLiveryConfig[]> = {
  spitfire: [
    {
      id: 'spitfire_raf_classic',
      aircraftType: 'spitfire',
      name: '皇家空軍歐陸迷彩',
      historicalName: 'RAF Temperate Land Camouflage',
      description: '經典英國皇家空軍歐陸戰區深綠與海灰迷彩塗裝，翼端飾有鮮明識別黃帶。',
      swatchPrimary: '#2d3a29',
      swatchSecondary: '#475569',
      swatchAccent: '#f59e0b',
      costMaterials: 0,
    },
    {
      id: 'spitfire_pacific_sea',
      aircraftType: 'spitfire',
      name: '太平洋第 81 中隊海天藍',
      historicalName: 'Pacific Theater Sea Blue',
      description: '部署於太平洋海域防空的深海藍海天塗裝，在高空與碧海環境具備極高隱蔽性。',
      swatchPrimary: '#1e3a5f',
      swatchSecondary: '#0f243e',
      swatchAccent: '#38bdf8',
      costMaterials: 3,
    },
    {
      id: 'spitfire_desert_sand',
      aircraftType: 'spitfire',
      name: '北非沙漠荒原黃沙',
      historicalName: 'Desert Air Force Mid-Stone',
      description: '北非戰線第八軍團航空隊沙漠迷彩，紅土與黃沙斑紋適合低空近距空戰。',
      swatchPrimary: '#b4884d',
      swatchSecondary: '#715332',
      swatchAccent: '#dc2626',
      costMaterials: 3,
    },
    {
      id: 'spitfire_dday_stripes',
      aircraftType: 'spitfire',
      name: '諾曼第 D-Day 侵攻斑紋',
      historicalName: '1944 Invasion Stripes Special',
      description: '1944 年 6 月 6 日諾曼第登陸當日塗布的黑白相間防友軍誤擊條紋，極具歷史傳奇色彩。',
      swatchPrimary: '#1e293b',
      swatchSecondary: '#f8fafc',
      swatchAccent: '#f59e0b',
      costMaterials: 4,
    },
  ],
  mustang: [
    {
      id: 'mustang_red_tail',
      aircraftType: 'mustang',
      name: '塔斯基吉「紅尾天使」',
      historicalName: '332nd Fighter Group Red Tails',
      description: '二戰傳奇非裔飛行員第 332 戰鬥機大隊標誌性赤紅垂直尾翼與拋光金屬機身，護航轟炸機從不被擊落的榮譽之盾。',
      swatchPrimary: '#e2e8f0',
      swatchSecondary: '#dc2626',
      swatchAccent: '#f59e0b',
      costMaterials: 0,
    },
    {
      id: 'mustang_silver_bullet',
      aircraftType: 'mustang',
      name: '拋光電鍍全銀航空鋁',
      historicalName: 'Bare-Metal Polished Aluminum',
      description: '徹底去除所有迷彩底漆以追求極限減重與極速，高反光金屬鋁面在陽光下耀眼奪目。',
      swatchPrimary: '#f1f5f9',
      swatchSecondary: '#94a3b8',
      swatchAccent: '#0284c7',
      costMaterials: 3,
    },
    {
      id: 'mustang_olive_drab',
      aircraftType: 'mustang',
      name: '美陸航第八航空軍橄欖綠',
      historicalName: 'USAAF Standard Olive Drab',
      description: '歐戰初期標準暗綠消光迷彩，座艙前噴塗黑色防眩目消光區以保護飛行員視力。',
      swatchPrimary: '#3a4735',
      swatchSecondary: '#64748b',
      swatchAccent: '#f59e0b',
      costMaterials: 3,
    },
    {
      id: 'mustang_blue_nosed',
      aircraftType: 'mustang',
      name: '博德尼「藍鼻刺客」',
      historicalName: '352nd FG Blue Nosed Bastards',
      description: '第 352 戰鬥大隊標誌性天藍色機首整流罩與銀翼，為納粹空軍最敬畏的空中王牌獵手。',
      swatchPrimary: '#2563eb',
      swatchSecondary: '#e2e8f0',
      swatchAccent: '#dc2626',
      costMaterials: 4,
    },
  ],
  dauntless: [
    {
      id: 'dauntless_pacific_two_tone',
      aircraftType: 'dauntless',
      name: '珊瑚海二色海軍迷彩',
      historicalName: 'US Navy Non-Specular Two-Tone',
      description: '美國海軍俯衝轟炸機標準上部非反光深海藍與下部珍珠白二色迷彩，搭配醒目白星國籍標誌。',
      swatchPrimary: '#1e3a5f',
      swatchSecondary: '#f8fafc',
      swatchAccent: '#dc2626',
      costMaterials: 0,
    },
    {
      id: 'dauntless_enterprise_dark',
      aircraftType: 'dauntless',
      name: '企業號深海暗夜藍',
      historicalName: 'USS Enterprise Dark Sea Blue',
      description: '傳奇航艦「大 E」企業號艦載第 6 偵察轟炸中隊全機暗海藍高光澤抗腐蝕塗裝。',
      swatchPrimary: '#0f2744',
      swatchSecondary: '#1e40af',
      swatchAccent: '#fbbf24',
      costMaterials: 3,
    },
    {
      id: 'dauntless_midway_avenger',
      aircraftType: 'dauntless',
      name: '中途島決戰戰損灰白',
      historicalName: 'Midway 1942 Weathered Grey',
      description: '中途島海戰擊沉赤城、加賀的傳奇戰功塗裝，帶有鹽霧侵蝕的戰場舊化質感。',
      swatchPrimary: '#475569',
      swatchSecondary: '#cbd5e1',
      swatchAccent: '#ea580c',
      costMaterials: 3,
    },
    {
      id: 'dauntless_atlantic_subhunter',
      aircraftType: 'dauntless',
      name: '大西洋反潛巡航消光白',
      historicalName: 'Atlantic Anti-Submarine Scheme',
      description: '大西洋獵殺 U 型潛艇專用超淺灰與純白反光塗裝，極度適應厚重雲層與海霧空域。',
      swatchPrimary: '#f8fafc',
      swatchSecondary: '#64748b',
      swatchAccent: '#0ea5e9',
      costMaterials: 4,
    },
  ],
  hurricane: [
    {
      id: 'hurricane_battle_of_britain',
      aircraftType: 'hurricane',
      name: '不列顛之役不屈綠棕',
      historicalName: 'Battle of Britain RAF Green/Earth',
      description: '在 1940 年不列顛空戰中擊落最多納粹戰機的功勳綠棕迷彩，厚重堅固的皇牌防禦色。',
      swatchPrimary: '#2d3a29',
      swatchSecondary: '#5c4827',
      swatchAccent: '#f59e0b',
      costMaterials: 0,
    },
    {
      id: 'hurricane_night_reaper',
      aircraftType: 'hurricane',
      name: '夜間截擊消光暗黑',
      historicalName: 'Night Reaper All-Black Special',
      description: '英國夜間空戰王牌專屬全機消光黑塗裝，夜間配合探照燈與機載雷達神出鬼沒。',
      swatchPrimary: '#171717',
      swatchSecondary: '#262626',
      swatchAccent: '#ef4444',
      costMaterials: 3,
    },
    {
      id: 'hurricane_desert_tomahawk',
      aircraftType: 'hurricane',
      name: '地中海馬爾他要塞黃沙',
      historicalName: 'Malta Defender Desert Scheme',
      description: '保衛地中海不沉航母馬爾他島期間的紅土與泥金迷彩，下表面噴塗天青藍。',
      swatchPrimary: '#b4884d',
      swatchSecondary: '#78350f',
      swatchAccent: '#38bdf8',
      costMaterials: 3,
    },
    {
      id: 'hurricane_soviet_winter',
      aircraftType: 'hurricane',
      name: '東線紅軍防衛雪地白',
      historicalName: 'Soviet Lend-Lease Winter White',
      description: '租借法案抵達蘇聯北極航線的冬季雪地臨時白漆塗裝，配備紅色空軍五角星。',
      swatchPrimary: '#f1f5f9',
      swatchSecondary: '#334155',
      swatchAccent: '#dc2626',
      costMaterials: 4,
    },
  ],
};

export function getLiveryById(aircraft: AircraftModelType, liveryId?: string): AircraftLiveryConfig {
  const list = AIRCRAFT_LIVERIES[aircraft] || AIRCRAFT_LIVERIES.spitfire;
  if (!liveryId) return list[0];
  const found = list.find(l => l.id === liveryId);
  return found || list[0];
}
